version: '2'
services:
  db:
    container_name: odoo16_db
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: always            
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  web:
    container_name: odoo16_web
    image: odoo:16
    depends_on:
      - db
    ports:
      - "16005:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always  